---
# TODO: implement latex installation
- name: Install latex
  debug:
    msg: "To install latex:
      * download the iso image from http://ctan.dcc.uchile.cl/systems/texlive/Images/
      * sudo mount -o loop texlive.iso /mnt
      * cd /mnt
      * sudo ./install-tl
      * add the path to ~/.profile with: 'export PATH=/usr/local/texlive/2020/bin/x86_64-linux:$PATH'
      "
- name: Install Texstudio
  debug:
    msg: "To install Texstudio:
      * download from https://www.texstudio.org/
      * sudo dpkg -i texstudio-qt4_2.12.22-1_amd64.deb
      "