---
- name: "Custon protoc version"
  pause:
    prompt: "Hello: By default protoc 3.11.3 will be installed\n
    Do you want to install custom protoc version? (yes/no)"
  register: isCustomRequired

- name: "protoc_custom_release_version"
  pause:
    prompt: "Choose from here available versions: https://mvnrepository.com/artifact/com.google.protobuf/protoc\n
    Enter the protoc version you want to install. eg 3.11.3"
  register: protoc_custom_release_version
  when: isCustomRequired.user_input == 'yes'

- name: Overriding protoc version to install
  set_fact:
    protoc_release_version: "{{ protoc_custom_release_version.user_input }}"
  when: protoc_custom_release_version is not skipped

- name: Install protoc
  debug:
      msg: "Installing protoc"

- name: previous clearing
  shell: rm -rf /tmp/protoc && mkdir /tmp/protoc
  args:
    warn: false

- name: pull protoc binaries
  get_url:
    url: "https://github.com/google/protobuf/releases/download/v{{protoc_release_version}}/protoc-{{protoc_release_version}}-linux-x86_64.zip" #"https://bintray.com/consensys/binaries/download_file?file_path=protoc-{{ protoc_release_version}}.tar.gz"
    dest: "/tmp/protoc/protoc.tar.gz"

- name: Extract the protoc tarball  
  unarchive:
        src: "/tmp/protoc/protoc.tar.gz"
        dest: /tmp/protoc
        copy: no

- name: Deleting old folders
  shell: rm -rf /usr/local/protoc
  args:
    warn: false
  become: yes
  become_user: root

- name: moving files to /usr
  shell: mv /tmp/protoc /usr/local
  become: yes
  become_user: root

- name: Deleting old installed versions of protoc
  file:
       path: /usr/bin/{{ item.dest }}
       state: absent
  with_items:
        - { dest: "protoc" }
        - { dest: "protoc.bat" }
  become: yes
  become_user: root

- name: Symbolic link for protoc
  file:
        src: "/usr/local/protoc/bin/{{ item.src }}"
        dest: "/usr/bin/{{ item.dest }}"
        state: link
  with_items:
        - { src: "protoc", dest: "protoc" }
  become: yes
  become_user: root

- name: clearing unnecessary folders
  shell: rm -rf /tmp/protoc && rm -rf /tmp/protoc
  args:
    warn: false