---
- name: Installer
  import_tasks: "install.yaml"
  when: " whatSoftware == '1' "
  become_user: "{{user}}"

- name: Install protoc
  import_tasks: "install-protoc.yaml"
  when: " whatSoftware == '2' "
  become_user: "{{user}}"

- name: Install laTex
  import_tasks: "install-latex.yaml"
  when: " whatSoftware == '3' "
  become_user: "{{user}}"

- name: Install Zshell
  import_tasks: "install-zshell.yaml"
  when: " whatSoftware == '4' "
  become_user: "{{user}}"