---
- name: Set zookeeper
  debug:
    msg: "Setting Kafka directory for zookeeper "

- name: Creating folder for zookeeper
  shell: rm -rf ~/kafka/data/zookeeper && mkdir -p ~/kafka/data/zookeeper

- name: Set dataDir for zookeeper
  shell: export ZOOKEEPER_FOLDER=$HOME/kafka/data/zookeeper  && sed -i "s@dataDir=/tmp/zookeeper@dataDir=$ZOOKEEPER_FOLDER@"  $HOME/kafka/config/zookeeper.properties