---
- name: Install kafka
  debug:
    msg: "Setting Kafka directory ... "

- name: Creating folder for data
  shell: rm -rf ~/kafka/data/kafka && mkdir -p ~/kafka/data/kafka

- name: Set log.dirs for Kafka
  shell: export KAFKA_FOLDER=$HOME/kafka/data/kafka  && sed -i "s@log.dirs=/tmp/kafka-logs@log.dirs=$KAFKA_FOLDER@"  $HOME/kafka/config/server.properties